version: "3.8"
services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lost_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data/db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lost_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    build:
      context: ./lost-in-europe
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./lost-in-europe:/usr/src/app
