FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install -f
# CMD ["yarn", "add", "&&", "yarn", "migration:run", "&&", "yarn", "start:dev"]
CMD yarn migration:run \
    && yarn start:dev
